TOPICS = [
    "Science - physics, chemistry, biology, astronomy, etc.",
    "Mathematics - algebra, geometry, calculus, statistics, etc.",
    "Technology - computers, engineering, AI, robotics, etc.",
    "Business - economics, finance, marketing, management, entrepreneurship",
    "History - ancient, medieval, modern, world history, military history",
    "Geography - countries, capitals, landscapes, maps, oceans, rivers",
    "Literature - poetry, novels, plays, short stories, genres, authors",
    "Philosophy - logic, ethics, political philosophy, existentialism",
    "Psychology - cognition, development, disorders, therapy, social psychology",
    "Sociology - culture, demographics, institutions, social change, inequality",
    "Politics - political systems, ideologies, voting, campaigns, public policy",
    "Law - constitutional law, criminal law, contracts, litigation, civil rights",
    "Medicine - anatomy, diseases, treatments, pharmaceuticals, medical specialties",
    "Religion - Christianity, Islam, Judaism, Buddhism, Hinduism, atheism",
    "Mythology - Greek, Roman, Norse, Egyptian, Native American myths",
    "Art - art history, painting, sculpture, architecture, music, theater",
    "Sports - individual and team sports, athletes, championships, training",
    "Cooking - recipes, ingredients, techniques, regional and ethnic cuisine",
    "Movies & TV - genre analysis, directors, actors, awards, popular shows",
    "News & Current Events - reporting on latest happenings around the world",
    "Culture - customs, values, gender roles, holidays, language, clothing",
    "Relationships - family, friends, romantic relationships, dating, marriage",
    "Education - teaching methods, curriculum, policy, higher education, vocational",
    "Transportation - cars, planes, trains, ships, public transit, infrastructure",
    "Communication - language acquisition, linguistics, rhetoric, social media",
    "Agriculture - farming techniques, crops, livestock, fisheries, forestry",
    "Housing & Architecture - interior design, urban planning, real estate, remodeling",
    "Nature & Environment - ecology, sustainability, conservation, renewable energy",
    "Travel & Tourism - destinations, lodging, adventure, culture, ecotourism",
    "Music - theory, genres, instruments, bands, composers, music history",
    "Fashion - designers, trends, modeling, retail, cosmetics, accessories",
    "Government - political systems, public administration, foreign policy, voting",
    "Warfare - military history, weapons, strategy, special operations forces",
    "Space - astronomy, spaceflight, exploration, space technology, universe",
    "Weather & Climate - meteorology, forecasting, natural disasters, seasons",
    "Food & Cooking - nutrition, recipes, diets, food science, restaurants",
    "Pets & Animals - breeds, care, veterinary medicine, wildlife, animal behavior",
    "Gardening - plants, landscaping, flowers, vegetables, lawn care, tools",
    "Home Improvement - repair, decor, renovation, tools, plumbing, electricity",
    "Personal Finance - budgeting, investing, taxes, insurance, retirement",
    "Exercise & Fitness - techniques, equipment, sports medicine, motivation",
    "Health & Medicine - biology, anatomy, diseases, treatments, wellness",
    "Mental Health - psychology, disorders, counseling, self-help, mindfulness",
    "Race & Ethnicity - cultures, discrimination, identity, immigration, diversity",
    "Gender & Sexuality - LGBTQ issues, feminism, roles, relationships, equality",
    "Employment - careers, human resources, resumes, workplace culture, unions",
    "Crime & Justice - laws, law enforcement, courts, prisons, investigations",
    "Social Issues - poverty, homelessness, human rights, community service",
    "Technology - computers, engineering, artificial intelligence, innovations",
    "Entertainment - movies, television, games, comedy, performing arts",
]
